---
defaults:

- scope:
    path: ''
  values:
    layout: default

- scope:
    type: posts
    path: gigs
  values:
    layout: gig
    pretitle:
      url:  /gigs
      text: Gigs

- scope:
    type: albums
  values:
    layout: album
    pretitle:
      url:  /albums
      text: Albums

- scope:
    type: posts
    path: blog
  values:
    layout: blost
    priority: 100

collections:
  albums:
    output: true

permalink: pretty
future: true

url: https://rawfunkmaharishi.uk
exclude:
  - scripts
  - spec
  - vendor
include:
  - .well-known
